### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by timohausmann** [demsking/image-downloader#10]
Hi. I can't get the example running:

```
  .then(({ filename, image }) => {
         ^
SyntaxError: Unexpected token {
```

Is my node.js uncapable of ECMA6 style?

Screenshot: http://imgur.com/a/EubGC

**Comment by demsking** [comment]
Destructuring feature is available since the v6.4.0 of NodeJS. So you need to upgrade your Node engine: `nvm use 6`
