### ISSUE TITLE
Error when trying to download image with content-type: text/html

### ISSUE THREAD

**Issue by pablonm3** [demsking/image-downloader#11]
This is more a question, i don't think its a problem with the module, but i can not figure out how to solve it,
i have a image url that when i request it the content-type header is: text/html, however when i go to the url on my browser it just loads the image and i can dowload it. The url is: https://www.bing.com/cr?IG=782EA0775DB14489B5B7220BB2DA0614&CID=23CE88AA1A8B64432B0D826A1B8D654F&rd=1&h=Cnjb8tz-5MkBUKE5JOrIlICVidI4wE-LJW_RONjobHU&v=1&r=https%3a%2f%2fwww.socialtalent.co%2fwp-content%2fuploads%2f2015%2f02%2fBooks-for-Recruiters.jpg&p=DevEx,5008.1

Is there some walk around in order to download that image? thanks!
ps: I have seen other service that is able to download that image from the url to their server so i think there must be a way to do it

**Comment by demsking** [comment]
The link you're trying to download is a Bing redirection link to `https://www.socialtalent.co/wp-content/uploads/2015/02/Books-for-Recruiters.jpg`. In addition, the server returns a 403 code when trying to access it from `image-downloader`, so you cannot download it with just `image-downloader`.
