### ISSUE TITLE
Unexpected token = , while running application

### ISSUE THREAD

**Issue by kartheekaleti** [demsking/image-downloader#14]
Hi Team,

Found the below issue while running the application " node server.js",

***/node_modules/image-downloader/index.js:14
const downloader = (options = {}) => {
                  
SyntaxError: Unexpected token =

Any idea ?

Greetings,
Karthee

**Comment by demsking** [comment]
Seems that your NodeJS is old.
You need NodeJS `>=6.10.1` to use this package.
