### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by madc0w** [demsking/image-downloader#15]
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
=> Modified -- restarting.
W20170926-18:17:35.090(2)? (STDERR) packages\modules.js:3021
W20170926-18:17:35.092(2)? (STDERR) const downloader = (options = {}) => {
W20170926-18:17:35.093(2)? (STDERR)                             ^
W20170926-18:17:35.094(2)? (STDERR)
W20170926-18:17:35.095(2)? (STDERR) SyntaxError: Unexpected token =
W20170926-18:17:35.096(2)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20170926-18:17:35.097(2)? (STDERR)     at C:\Users\hifi\git\spoticle\.meteor\local\build\programs\server\boot.js:331:30
W20170926-18:17:35.098(2)? (STDERR)     at Array.forEach (native)
W20170926-18:17:35.100(2)? (STDERR)     at Function._.each._.forEach (C:\Users\hifi\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20170926-18:17:35.102(2)? (STDERR)     at C:\Users\hifi\git\spoticle\.meteor\local\build\programs\server\boot.js:158:5
W20170926-18:17:35.102(2)? (STDERR)     at C:\Users\hifi\git\spoticle\.meteor\local\build\programs\server\boot.js:387:5
W20170926-18:17:35.103(2)? (STDERR)     at Function.run (C:\Users\hifi\git\spoticle\.meteor\local\build\programs\server\profile.js:510:12)
W20170926-18:17:35.104(2)? (STDERR)     at C:\Users\hifi\git\spoticle\.meteor\local\build\programs\server\boot.js:386:11

**Comment by demsking** [comment]
Seems that your NodeJS is old.
You need NodeJS `>=6.10.1` to use this package.
