### ISSUE TITLE
Wrong assumption about file name

### ISSUE THREAD

**Issue by DmitryMyadzelets** [demsking/image-downloader#16]
There is [wrong assumption](https://github.com/demsking/image-downloader/blob/master/index.js#L36l) that the file name always has an extension. Thus, providing a file name with no extension results in the error `Error: ENOTDIR: not a directory, open [filename]`.

In general, images can be served without extensions ([see SO](https://stackoverflow.com/questions/5110384/can-i-use-images-without-extension-in-img) as an intro), since browsers look at the `Content-type` header property.

As a use case, the [`multer`](https://github.com/expressjs/multer) saves images with no extension by default.

To my opinion, that code should be removed. It would also make this module independent of `path` module.

**Comment by demsking** [comment]
This issue has been moved to https://gitlab.com/demsking/image-downloader/issues/16
