### ISSUE TITLE
Progress event

### ISSUE THREAD

**Issue by BransonGitomeh** [demsking/image-downloader#8]
is there a way to get a progress even thats emited?. its usefull for a cli application to make some sort of fancy progress bar

**Comment by demsking** [comment]
It's possible to add a progress event support.
I'll work on that next weekend.

**Comment by Pranoy1c** [comment]
Any luck with progress event?

**Comment by demsking** [comment]
This issue has been moved to https://gitlab.com/demsking/image-downloader/issues/8
